create table public.requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  "firstName" text,
  "middleInitial" text,
  "lastName" text,
  age int,
  address text,
  purpose text,
  status text default 'pending',
  type text default 'Barangay Clearance',
  user_id uuid references auth.users(id)
);
